// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdUCoT13IZXEmwoxIDPiIfb0D2M6_tEI',
    appId: '1:366120527293:web:0a430461237f0fc17eded4',
    messagingSenderId: '366120527293',
    projectId: 'cmsc190-jlpp',
    authDomain: 'cmsc190-jlpp.firebaseapp.com',
    storageBucket: 'cmsc190-jlpp.appspot.com',
    measurementId: 'G-S8R2QCM37N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvADh2jTDRtjCQCoGwM3zvoXs9zXw45ks',
    appId: '1:366120527293:android:65f36b519f92454f7eded4',
    messagingSenderId: '366120527293',
    projectId: 'cmsc190-jlpp',
    storageBucket: 'cmsc190-jlpp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpP3u5e6Z4dGMZhF1pGi640_gMRWdzP2s',
    appId: '1:366120527293:ios:453facbcb5a27de47eded4',
    messagingSenderId: '366120527293',
    projectId: 'cmsc190-jlpp',
    storageBucket: 'cmsc190-jlpp.appspot.com',
    iosClientId: '366120527293-ph4866cnlpfbpu2g1aa8vppj1vulbpmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaLifeguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpP3u5e6Z4dGMZhF1pGi640_gMRWdzP2s',
    appId: '1:366120527293:ios:453facbcb5a27de47eded4',
    messagingSenderId: '366120527293',
    projectId: 'cmsc190-jlpp',
    storageBucket: 'cmsc190-jlpp.appspot.com',
    iosClientId: '366120527293-ph4866cnlpfbpu2g1aa8vppj1vulbpmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphaLifeguard',
  );
}
